import { Inter, Newsreader } from "next/font/google";
import Header from "../components/Header.jsx";
import Footer from "../components/Footer.jsx";
const inter = Inter({
    subsets: ["latin"], // Include Latin characters
    weights: ["400", "700"], // Include regular and bold weights
});

export const newsreader = Newsreader({
    subsets: ["latin"], // Include Latin characters
    weights: ["400", "700"], // Include regular and bold weights
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${inter.className}`}>
                <main>{children}</main>
            </body>
        </html>
    );
}
